### PR TITLE
Upgrade to angular v14

### LINKED ISSUE #7: Missing angular 14 support
Angular 14 not yet supported.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: <project-name>@0.0.0
npm ERR! Found: @angular/common@14.0.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~14.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from angular-remix-icon@3.0.0
npm ERR! node_modules/angular-remix-icon
npm ERR!   angular-remix-icon@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### PR DESCRIPTION
**Pull request by niklaskappler**
Closes #7

### CODE REVIEW

**Comment by adisreyaj** [comment]
Thanks for the PR. Will validate it and also check the standalone route before pushing this out to npm.

**Comment by martinvplopez** [comment]
Hi! Thank you for developing this tool, it makes it much easier [and lighter ;)], when is this merge coming out? Will be looking forward to having it ready for our angular project! 
Greetings

**Comment by BarkhatovN** [comment]
Merge this one please <3

**Comment by adisreyaj** [comment]
> Merge this one please <3

Sorry for the long delay. I'll try and get it merged.

**Pull request merged**
